# Site settings
title: Girls Coding Day
subTitle: 架起女性与编程的桥梁
description: 关注我们公众号/微博：codingirlsclub
keywords: 女性, 编程, 教育, 公益
author: 文洋
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
